<?php

namespace ImieNetwork\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypecontratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypecontratRepository extends EntityRepository
{
}
