<?php

namespace ImieNetwork\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository
{
    public function offresActivesParUtilisateur($utilisateur)
    {
        $qb = $this->em()->createQueryBuilder();

        $qb->select('o')
       ->from('ImieNetworkSiteBundle:offre', 'o')
       ->where('o.date_fin_publication > :datecourant')
       ->andWhere('o.utilisateur = :idUtilisateur')
       ->setParameter('datecourant', new \Datetime(date('d-m-Y')))
       ->setParameter('idUtilisateur', $utilisateur.id)
       ->orderBy('o.date_fin_publication', 'DESC');

        return $qb->getQuery()
               ->getResult();
    }
    
    public function offresNonActivesParUtilisateur($utilisateur)
    {
        $qb = $this->em()->createQueryBuilder();

        $qb->select('o')
       ->from('ImieNetworkSiteBundle:offre', 'o')
       ->where('o.date_fin_publication < :datecourant')
       ->andWhere('o.utilisateur = :idUtilisateur')
       ->setParameter('datecourant', new \Datetime(date('d-m-Y')))
       ->setParameter('idUtilisateur', $utilisateur.id)
       ->orderBy('o.date_fin_publication', 'DESC');

        return $qb->getQuery()
               ->getResult();
    }
    
    public function findSearch($ville, $contrat)
    {
        if($contrat == "empty")
        {
            $qb = $this->_em->createQuery('SELECT o
                FROM ImieNetworkSiteBundle:Offre o
                WHERE o.ville = :idville'
            )
            ->setParameter('idville', $ville);
            
            $res = $qb->getResult();
        }
        if($ville == "empty")
        {
            $qb = $this->_em->createQuery('SELECT o
                FROM ImieNetworkSiteBundle:Offre o
                WHERE o.type_contrat = :idcontrat'
            )
            ->setParameter('idcontrat', $contrat);
            
            $res = $qb->getResult();
        }
        if($ville != "empty" && $contrat != "empty")
        {
            
            $qb = $this->_em->createQuery('SELECT o
                FROM ImieNetworkSiteBundle:Offre o
                WHERE o.ville = :idville and o.type_contrat = :idcontrat'
            )
            ->setParameter('idville', $ville)
            ->setParameter('idcontrat', $contrat);
            
            $res = $qb->getResult();
        }
        return $res;
    }
}
