<?php

namespace ImieNetwork\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OffrevilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffrevilleRepository extends EntityRepository
{
}
